(()=>{
  const DATA=window.COURSE_DATA,$=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
  const savedLang=localStorage.getItem('ttro-lang')||'ja'; window.APP_STATE={lang:['ja','en','both'].includes(savedLang)?savedLang:'ja'};
  const ui={
    ja:{progress:'学習進捗',reset:'進捗をリセット',overview:'解説',points:'要点',formulas:'数式・キー',interactive:'操作して確認',related:'関連定義',complete:'完了にする',completed:'完了済み',copy:'リンクをコピー',prev:'前へ',next:'次へ',openLab:'このLabを開く',pdfPage:'PDFで対応ページ',sourceNote:'PDFは全154ページです。1〜77ページが日本語、78〜154ページが英語で、JP p.n と EN p.n は77ページ差で1対1対応します。',search:'検索',noResults:'該当する項目がありません',pdfTitle:'日英統合PDF',pdfDesc:'1冊154ページです。PDF 1〜77ページは日本語、78〜154ページは英語です。ページ番号から言語を自動判定し、JP/EN切替では対応ページへ移動します。'},
    en:{progress:'Progress',reset:'Reset progress',overview:'Explanation',points:'Key points',formulas:'Formulas / keys',interactive:'Interactive lab',related:'Related definitions',complete:'Mark complete',completed:'Completed',copy:'Copy link',prev:'Previous',next:'Next',openLab:'Open this lab',pdfPage:'Open paired PDF page',sourceNote:'The PDF has 154 pages total: pages 1-77 are Japanese and pages 78-154 are English. JP p.n and EN p.n are paired with an offset of 77 pages.',search:'Search',noResults:'No matching items',pdfTitle:'Bilingual 154-page PDF',pdfDesc:'This is one 154-page PDF: pages 1-77 are Japanese and pages 78-154 are English. The page number determines the language, and switching JP/EN jumps to the paired page.'}
  };
  const L=()=>window.APP_STATE.lang,T=k=>ui[L()==='en'?'en':'ja'][k]||k,esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const lesson=id=>DATA.lessons.find(l=>l.id===id)||DATA.lessons[0],ch=id=>DATA.chapters.find(c=>c.id===id),completed=()=>new Set(JSON.parse(localStorage.getItem('ttro-completed')||'[]')),saveCompleted=s=>localStorage.setItem('ttro-completed',JSON.stringify([...s]));
  const displayTitle=l=>L()==='en'?l.en.title:L()==='both'?`${l.title} / ${l.en.title}`:l.title;
  const displaySubtitle=l=>L()==='en'?l.en.subtitle:L()==='both'?`${l.subtitle} / ${l.en.subtitle}`:l.subtitle;
  const chapterName=c=>L()==='en'?c.en:L()==='both'?`${c.ja} / ${c.en}`:c.ja;
  const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1700)};
  function init(){initTheme();bindChrome();setLangUI();buildSidebar();updateProgress();addEventListener('hashchange',()=>route());route();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
  function initTheme(){const theme=localStorage.getItem('ttro-theme')||'system',dark=theme==='dark'||(theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';$('#themeToggle').onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('ttro-theme',n)}}
  function applyLanguage(lang){window.APP_STATE.lang=lang;localStorage.setItem('ttro-lang',lang);document.documentElement.lang=lang==='en'?'en':'ja';setLangUI();buildSidebar()}
  function setLanguage(lang,{reroute=true}={}){const r=parseRoute();applyLanguage(lang);if(!reroute)return;if(r.type==='print'&&lang!=='both'){const info=pdfPageInfo(Number(r.arg)||1),target=logicalToAbsolute(info.logical,lang),hash=`#/print/${target}`;if(location.hash!==hash)location.hash=hash;else route(false)}else route(false)}
  function bindChrome(){
    $('#sidebarToggle').onclick=openSidebar;$('#sidebarBackdrop').onclick=closeSidebar;
    $$('.lang-switch button').forEach(b=>b.onclick=()=>setLanguage(b.dataset.lang));
    $('#resetProgress').onclick=()=>{if(confirm(L()==='en'?'Reset all lesson progress?':'すべての学習進捗をリセットしますか？')){localStorage.removeItem('ttro-completed');updateProgress();buildSidebar();route(false)}};
    $('#searchOpen').onclick=openSearch;const si=$('#globalSearch');si.addEventListener('input',()=>search(si.value));si.addEventListener('keydown',searchKey);$('#searchDialog').addEventListener('close',()=>{si.value='';$('#searchResults').innerHTML=''});
    document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')closeSidebar();if(!$('#searchDialog').open&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&e.altKey){if(e.key==='ArrowRight')moveLesson(1);if(e.key==='ArrowLeft')moveLesson(-1)}})
  }
  function setLangUI(){$$('.lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===L()));$('[data-i18n="progress"]').textContent=T('progress');$('#resetProgress').textContent=T('reset')}
  function openSidebar(){$('#sidebar').classList.add('open');$('#sidebarBackdrop').hidden=false} function closeSidebar(){$('#sidebar').classList.remove('open');$('#sidebarBackdrop').hidden=true}
  function parseRoute(){const raw=(location.hash||'#/course/p01').replace(/^#\/?/,'');const [type='course',arg='p01',extra]=raw.split('/');return{type,arg,extra,lessonId:type==='course'?arg:null}}
  function route(scroll=true){const r=parseRoute();$$('.topnav a').forEach(a=>{const key=a.dataset.nav;const active=(r.type==='playground'&&key==='labs')||(r.type===key);a.classList.toggle('active',active)});if(r.type==='playground')renderPlayground(r.arg||'easing');else if(r.type==='labs')renderLabs();else if(r.type==='reference')renderReference(r.arg);else if(r.type==='print')renderPrint(Number(r.arg)||1);else renderCourse(r.lessonId||'p01');buildSidebar();updateProgress();closeSidebar();if(scroll)scrollTo({top:0,behavior:'auto'})}
  function buildSidebar(){const active=parseRoute().lessonId,done=completed();$('#chapterNav').innerHTML=DATA.chapters.map(c=>{const ls=DATA.lessons.filter(l=>l.chapter===c.id);return `<section class="chapter-block"><button class="chapter-title" type="button" style="--chapter-color:${c.color}"><span class="dot"></span><span>${esc(chapterName(c))}</span><span class="chev">⌄</span></button><div class="chapter-lessons">${ls.map(l=>`<a class="lesson-link ${l.id===active?'active':''}" href="#/course/${l.id}"><span class="lesson-index">${String(l.sourcePage).padStart(2,'0')}</span><span>${esc(displayTitle(l))}</span>${done.has(l.id)?'<span class="done-mark">✓</span>':''}</a>`).join('')}</div></section>`}).join('');$$('.chapter-title').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('collapsed'))}
  function updateProgress(){const n=completed().size,total=DATA.lessons.length,p=Math.round(n/total*100);$('#progressPct').textContent=p+'%';$('#progressBar').style.width=p+'%'}
  function moveLesson(d){const r=parseRoute();if(r.type!=='course')return;const i=DATA.lessons.findIndex(l=>l.id===r.lessonId),n=DATA.lessons[i+d];if(n)location.hash=`#/course/${n.id}`}
  function relatedDefs(l){return DATA.definitions.filter(d=>d.lessons.includes(l.id))}
  function bodyHTML(l){const ja=l.body.map(p=>`<p>${esc(p)}</p>`).join(''),en=l.en.body.map(p=>`<p>${esc(p)}</p>`).join('');if(L()==='ja')return ja;if(L()==='en')return `<div class="en-block">${en}</div>`;return `<div class="bilingual-block"><div><div class="context-label">日本語</div>${ja}</div><div><div class="context-label">English</div>${en}</div></div>`}
  function pointsHTML(l){const ja=l.keyPoints||[],en=l.en.keyPoints||[];if(L()==='ja')return ja;if(L()==='en')return en;const m=Math.max(ja.length,en.length),out=[];for(let i=0;i<m;i++)out.push(`${ja[i]?esc(ja[i]):''}${ja[i]&&en[i]?' / ':''}${en[i]?esc(en[i]):''}`);return out}
  function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
  function logicalToAbsolute(page,lang){const per=DATA.meta.pagesPerLanguage,p=clamp(Number(page)||1,1,per);return p+(lang==='en'?per:0)}
  function pdfPageInfo(page){const per=DATA.meta.pagesPerLanguage,total=DATA.meta.pdfTotalPages,absolute=clamp(Number(page)||1,1,total),lang=absolute>per?'en':'ja',logical=lang==='en'?absolute-per:absolute;return{absolute,logical,lang}}
  function renderCourse(id){const l=lesson(id),c=ch(l.chapter),i=DATA.lessons.indexOf(l),prev=DATA.lessons[i-1],next=DATA.lessons[i+1],done=completed(),defs=relatedDefs(l),points=pointsHTML(l);localStorage.setItem('ttro-last-page',l.sourcePage);document.title=`${displayTitle(l)} - Ttro Intro Engine`;
    const lab=l.lab?`<section class="lab-inline"><div class="lab-kicker">${T('interactive')}</div><div id="inlineLab"></div><div class="lab-open-row"><a class="primary-btn big-action" href="#/playground/${l.lab}">${T('openLab')} →</a></div></section>`:'';
    $('#view').innerHTML=`<div class="view-shell"><header class="lesson-header" style="--chapter-color:${c.color}"><div class="eyebrow"><span class="chapter-chip">${esc(chapterName(c))}</span><span>·</span><span>${String(l.sourcePage).padStart(2,'0')} / 77</span></div><h1 class="lesson-title">${esc(displayTitle(l))}</h1><p class="lesson-subtitle">${esc(displaySubtitle(l))}</p><div class="lesson-actions"><button id="completeBtn" class="ghost-btn ${done.has(l.id)?'done':''}" type="button">${done.has(l.id)?'✓ '+T('completed'):T('complete')}</button><button id="copyBtn" class="ghost-btn" type="button">↗ ${T('copy')}</button><a class="ghost-btn" href="#/print/${logicalToAbsolute(l.sourcePage,L()==='en'?'en':'ja')}">PDF ${logicalToAbsolute(l.sourcePage,L()==='en'?'en':'ja')}</a>${l.lab?`<a class="primary-btn" href="#/playground/${l.lab}">${T('openLab')} →</a>`:''}</div></header><div class="content-grid"><article class="article"><section class="section card"><h2>${T('overview')}</h2>${bodyHTML(l)}</section>${points.length?`<section class="section"><h2>${T('points')}</h2><ul class="key-list">${points.map(p=>`<li>${p}</li>`).join('')}</ul></section>`:''}${l.formulas.length?`<section class="section"><h2>${T('formulas')}</h2><div class="formula-grid">${l.formulas.map(f=>`<div class="formula-card"><code>${esc(f)}</code></div>`).join('')}</div></section>`:''}${lab}<div class="callout mini-card source-note"><div class="context-label">JP / EN pairing</div><p>${esc(T('sourceNote'))}</p></div><footer class="lesson-footer">${prev?`<a class="prevnext" href="#/course/${prev.id}"><span>← ${T('prev')}</span><strong>${esc(displayTitle(prev))}</strong><small>${String(prev.sourcePage).padStart(2,'0')} / 77</small></a>`:'<span></span>'}${next?`<a class="prevnext next" href="#/course/${next.id}"><span>${T('next')} →</span><strong>${esc(displayTitle(next))}</strong><small>${String(next.sourcePage).padStart(2,'0')} / 77</small></a>`:''}</footer></article><aside class="side-context"><div class="mini-card"><div class="context-label">${T('related')}</div><div class="context-links">${defs.length?defs.map(d=>`<a class="term-chip" href="#/reference/${d.id}">${esc(d.name)}</a>`).join(''):'<span class="muted">—</span>'}</div></div><div class="mini-card"><div class="context-label">${L()==='en'?'This section':'このセクション'}</div><ol>${DATA.lessons.filter(x=>x.chapter===l.chapter).map(x=>`<li><a href="#/course/${x.id}" ${x.id===l.id?'class="current"':''}>${esc(displayTitle(x))}</a></li>`).join('')}</ol></div>${l.lab?`<div class="mini-card lab-side-card"><div class="context-label">Interactive Lab</div><p>${esc(window.LABS.names[l.lab][L()==='en'?1:0])}</p><a class="primary-btn big-action" href="#/playground/${l.lab}">${T('openLab')} →</a></div>`:''}</aside></div></div>`;
    $('#completeBtn').onclick=()=>{const s=completed();s.has(l.id)?s.delete(l.id):s.add(l.id);saveCompleted(s);updateProgress();buildSidebar();renderCourse(l.id)};$('#copyBtn').onclick=()=>navigator.clipboard?.writeText(location.href).then(()=>toast(L()==='en'?'Link copied':'リンクをコピーしました')).catch(()=>{});if(l.lab)window.LABS.render(l.lab,$('#inlineLab'))
  }

  function renderLabs(){
    document.title='Lab - Ttro Intro Engine';
    const desc={
      easing:['Easing曲線・進行度・出力値を同期表示。','Inspect the easing curve, progress, and output in sync.'],
      rotate:['回転行列の各項と回転後座標を確認。','Inspect the rotation-matrix terms and rotated coordinates.'],
      camera:['World→Camera差分→回転→Zoom/Screenを追跡。','Trace World → camera offset → rotation → zoom/screen.'],
      timer:['秒・拍・進行度の関係を確認。','Inspect seconds, beats, and normalized progress.'],
      stamp:['時間条件→Position→VFX→Stampの流れを可視化。','Visualize time gate → Position → VFX → Stamp.'],
      particle:['時刻から粒子状態を再構成。','Reconstruct particle state from time.'],
      spline:['N+1個の制御点からN次ベジェを生成し、de Casteljauを表示。','Generate an N-degree Bézier from N+1 control points and show de Casteljau levels.'],
      memory:['*Listの番号運用を視覚化。','Visualize the *List slot policy.'],
      dependencies:['定義の依存関係を探索。','Explore definition dependencies.']
    };
    const cards=window.LABS.ids.map(id=>{const nm=window.LABS.names[id][L()==='en'?1:0];const d=desc[id][L()==='en'?1:0];const back=DATA.lessons.find(l=>l.lab===id);return `<a class="lab-card card" href="#/playground/${id}"><div class="lab-card-top"><span class="lab-card-kicker">INTERACTIVE LAB</span><span class="term-chip">Auto</span></div><h3>${esc(nm)}</h3><p>${esc(d)}</p>${back?`<small>${L()==='en'?'Linked lesson':'対応ページ'}: ${String(back.sourcePage).padStart(2,'0')} / 77</small>`:''}</a>`}).join('');
    $('#view').innerHTML=`<div class="view-shell"><header class="hero"><div class="eyebrow">INTERACTIVE LAB</div><h1>${L()==='en'?'Lab index':'Lab 一覧'}</h1><p>${L()==='en'?'Open any lab from here. Each lab starts in Auto Play mode and can be switched to manual control.':'ここから各Labを開けます。すべてのLabはAuto Playで始まり、必要に応じて手動操作へ切り替えられます。'}</p></header><section class="lab-overview">${cards}</section></div>`;
  }

  function renderPlayground(id){if(!window.LABS.ids.includes(id))id='easing';document.title=`${window.LABS.names[id][1]} - Lab - Ttro Intro Engine`;const back=DATA.lessons.find(l=>l.lab===id);$('#view').innerHTML=`<div class="view-shell playground-page"><header class="hero"><div class="eyebrow">INTERACTIVE LAB</div><h1>${esc(window.LABS.names[id][L()==='en'?1:0])}</h1><p>${L()==='en'?'Manipulate the values used by the engine and compare equations, internal state, and visible output.':'エンジン内部の値を直接操作し、数式・内部値・見た目の変化を同時に確認します。'}</p>${back?`<a class="ghost-btn big-action" href="#/course/${back.id}">← ${L()==='en'?'Back to lesson':'対応ページへ戻る'} ${back.sourcePage}</a>`:''}</header><div id="playgroundMount"></div></div>`;window.LABS.render(id,$('#playgroundMount'))}
  function renderReference(id){document.title='Reference - Ttro Intro Engine';const one=id?DATA.definitions.find(d=>d.id===id):null;const cards=(one?[one]:DATA.definitions).map(d=>`<article class="reference-card card"><h3>${esc(d.name)}</h3><p>${esc(L()==='en'?d.en:d.ja)}</p><div class="ref-rel"><div><small>${L()==='en'?'depends on':'依存'}</small><div>${d.deps.length?d.deps.map(x=>esc(DATA.definitions.find(z=>z.id===x)?.name||x)).join(' · '):'—'}</div></div><div><small>${L()==='en'?'used by':'利用先'}</small><div>${d.usedBy.length?d.usedBy.map(x=>esc(DATA.definitions.find(z=>z.id===x)?.name||x)).join(' · '):'—'}</div></div></div>${d.lessons.length?`<div class="context-links ref-lessons">${d.lessons.map(x=>{const l=lesson(x);return `<a class="term-chip" href="#/course/${x}">p.${l.sourcePage}</a>`}).join('')}</div>`:''}</article>`).join('');$('#view').innerHTML=`<div class="view-shell reference-page"><header class="hero"><div class="eyebrow">REFERENCE</div><h1>${L()==='en'?'Definition reference':'定義リファレンス'}</h1><p>${L()==='en'?'Jump between definitions and the exact course pages that use them.':'定義の責務・依存関係と、それを扱う講座ページを相互に移動できます。'}</p></header>${one?`<a class="ghost-btn" href="#/reference">← ${L()==='en'?'All definitions':'一覧へ'}</a>`:''}<div class="reference-grid">${cards}</div></div>`}
  function renderPrint(absolute){
    const per=DATA.meta.pagesPerLanguage,total=DATA.meta.pdfTotalPages,file=DATA.meta.pdfFile;
    const fallback=logicalToAbsolute(Number(localStorage.getItem('ttro-last-page'))||1,L()==='en'?'en':'ja');
    const info=pdfPageInfo(absolute||fallback);
    if(L()!=='both'&&L()!==info.lang)applyLanguage(info.lang);
    const src=`${encodeURI(file)}#page=${info.absolute}&view=FitH`,jpAbs=info.logical,enAbs=info.logical+per;
    document.title=`PDF p.${info.absolute} - Ttro Intro Engine`;
    $('#view').innerHTML=`<div class="view-shell print-page"><header class="hero"><div class="eyebrow">PDF · ${total} PAGES · ${info.lang.toUpperCase()}</div><h1>${T('pdfTitle')}</h1><p>${T('pdfDesc')}</p></header><section class="pdf-control card"><div class="pdf-pair"><button id="pdfJP" class="pdf-lang-card ${info.lang==='ja'?'active':''}" type="button"><small>Japanese · PDF p.${jpAbs}</small><strong>${info.logical}</strong><span>/ 77</span></button><button id="pdfEN" class="pdf-lang-card ${info.lang==='en'?'active':''}" type="button"><small>English · PDF p.${enAbs}</small><strong>${info.logical}</strong><span>/ 77</span></button></div><div class="pdf-jump"><label for="pdfPage">${L()==='en'?'PDF page (1-154)':'PDFページ（1〜154）'}</label><div><input id="pdfPage" type="number" min="1" max="${total}" value="${info.absolute}"><button id="pdfGo" class="primary-btn big-action" type="button">Go</button></div><small>${L()==='en'?'Pages 1-77 are Japanese; 78-154 are English. Entering an absolute page automatically selects the matching language.':'1〜77は日本語、78〜154は英語です。絶対ページ番号を入力すると言語を自動判定します。'}</small></div><div class="pdf-links"><a class="ghost-btn big-action" href="${src}" target="_blank" rel="noopener">${L()==='en'?'Open PDF page in a new tab':'このPDFページを新しいタブで開く'} ↗</a><a class="ghost-btn big-action" href="${encodeURI(file)}#page=${jpAbs}" target="_blank" rel="noopener">JP · PDF ${jpAbs}</a><a class="ghost-btn big-action" href="${encodeURI(file)}#page=${enAbs}" target="_blank" rel="noopener">EN · PDF ${enAbs}</a><a class="ghost-btn big-action" href="#/course/p${String(info.logical).padStart(2,'0')}">${L()==='en'?'Open matching web page':'対応Webページ'} →</a></div></section><div class="pdf-frame-wrap"><iframe class="pdf-frame" title="Ttro Intro Engine PDF page ${info.absolute}" src="${src}"></iframe></div></div>`;
    const jumpTo=(target,lang)=>{if(lang)setLanguage(lang,{reroute:false});const hash=`#/print/${target}`;if(location.hash!==hash)location.hash=hash;else route(false)};
    $('#pdfJP').onclick=()=>jumpTo(jpAbs,'ja');
    $('#pdfEN').onclick=()=>jumpTo(enAbs,'en');
    const go=()=>{const target=clamp(Number($('#pdfPage').value)||1,1,total),next=pdfPageInfo(target);if(L()!=='both')setLanguage(next.lang,{reroute:false});jumpTo(target,null)};
    $('#pdfGo').onclick=go;$('#pdfPage').onkeydown=e=>{if(e.key==='Enter')go()}
  }
  let searchSelection=0;function openSearch(){$('#searchDialog').showModal();setTimeout(()=>$('#globalSearch').focus(),0);search('')}function search(q){q=q.trim().toLowerCase();const lessonResults=DATA.lessons.filter(l=>!q||[l.title,l.subtitle,l.en.title,l.en.subtitle,...l.body,...l.en.body,...l.keyPoints,...l.en.keyPoints].join(' ').toLowerCase().includes(q)).slice(0,12).map(l=>({type:'lesson',title:displayTitle(l),sub:displaySubtitle(l),href:`#/course/${l.id}`})),defResults=DATA.definitions.filter(d=>q&&[d.name,d.ja,d.en].join(' ').toLowerCase().includes(q)).slice(0,6).map(d=>({type:'definition',title:d.name,sub:L()==='en'?d.en:d.ja,href:`#/reference/${d.id}`})),res=[...lessonResults,...defResults];searchSelection=0;$('#searchResults').innerHTML=res.length?res.map((r,i)=>`<div class="search-result ${i===0?'active':''}" data-href="${r.href}" data-i="${i}"><span class="result-type">${r.type}</span><span><strong>${esc(r.title)}</strong><small>${esc(r.sub)}</small></span></div>`).join(''):`<div class="empty-search">${T('noResults')}</div>`;$$('.search-result').forEach(x=>x.onclick=()=>{location.hash=x.dataset.href.slice(1);$('#searchDialog').close()})}
  function searchKey(e){const r=$$('.search-result');if(!r.length)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();searchSelection=(searchSelection+(e.key==='ArrowDown'?1:-1)+r.length)%r.length;r.forEach((x,i)=>x.classList.toggle('active',i===searchSelection));r[searchSelection].scrollIntoView({block:'nearest'})}if(e.key==='Enter'){e.preventDefault();location.hash=r[searchSelection].dataset.href.slice(1);$('#searchDialog').close()}}
  init();
})();
