(()=>{
  const D=()=>window.COURSE_DATA;
  const lang=()=>window.APP_STATE?.lang||'ja';
  const tx=(ja,en)=>lang()==='en'?en:ja;
  const fmt=(n,d=2)=>{const s=Number(n).toFixed(d);return s.includes('.')?s.replace(/0+$/,'').replace(/\.$/,''):s};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const deg=r=>r*Math.PI/180;
  const ease=(u,type,p)=>{
    u=clamp(u,0,1); p=+p;
    if(type==='linear')return u;
    if(type==='in')return Math.pow(u,p);
    if(type==='out')return 1-Math.pow(1-u,p);
    if(type==='inout')return u<.5?0.5*Math.pow(u*2,p):1-0.5*Math.pow((1-u)*2,p);
    return u;
  };
  const shell=(titleJa,titleEn,descJa,descEn,controls,stage)=>`<div class="lab-shell"><div class="lab-head"><div><div class="lab-kicker">Interactive Lab</div><h2>${tx(titleJa,titleEn)}</h2><p>${tx(descJa,descEn)}</p></div></div><div class="lab-grid"><div class="controls">${controls}</div><div>${stage}</div></div></div>`;
  const range=(id,labelJa,labelEn,min,max,step,val,unit='')=>`<div class="control"><div class="control-row"><label for="${id}">${tx(labelJa,labelEn)}</label><output id="${id}Out">${val}${unit}</output></div><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${val}"></div>`;
  const playBtns=()=>`<div class="play-row"><button class="primary-btn" data-play>▶ ${tx('再生','Play')}</button><button class="ghost-btn" data-reset>↺ ${tx('リセット','Reset')}</button></div>`;

  function renderEasing(m){
    const controls=`<div class="control"><label>${tx('Type','Type')}</label><div class="segmented" data-ease-type><button data-v="linear">Linear</button><button data-v="in">In</button><button class="active" data-v="out">Out</button><button data-v="inout">InOut</button></div></div>${range('easePower','Power','Power',1,6,.25,3)}${range('easeU','進行度 u','Progress u',0,1,.001,0)}<div class="control"><div class="control-row"><label>${tx('値域','Value range')}</label><output id="easeRangeOut">0 → 100</output></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:7px"><input id="easeStart" class="num-input" type="number" value="0"><input id="easeEnd" class="num-input" type="number" value="100"></div></div>${playBtns()}<div id="easeFormula" class="formula-live"></div>`;
    const stage=`<div class="stage" style="min-height:360px"><svg id="easeSvg" viewBox="0 0 620 360" role="img" aria-label="Easing graph"></svg></div><div id="easeReadout" class="readout-grid"></div>`;
    m.innerHTML=shell('Easing Playground','Easing Playground','曲線・進行度・実際の移動を同時に確認します。','Compare the curve, normalized progress, and actual motion at the same time.',controls,stage);
    let type='out',playing=false,raf=0,startTime=0;
    const uEl=m.querySelector('#easeU'),pEl=m.querySelector('#easePower'),sEl=m.querySelector('#easeStart'),eEl=m.querySelector('#easeEnd');
    m.querySelectorAll('[data-ease-type] button').forEach(b=>b.onclick=()=>{type=b.dataset.v;m.querySelectorAll('[data-ease-type] button').forEach(x=>x.classList.toggle('active',x===b));draw()});
    function draw(){
      const u=+uEl.value,p=+pEl.value,a=+sEl.value,b=+eEl.value,eu=ease(u,type,p),value=a+(b-a)*eu;
      m.querySelector('#easePowerOut').textContent=fmt(p,2);m.querySelector('#easeUOut').textContent=fmt(u,3);m.querySelector('#easeRangeOut').textContent=`${fmt(a)} → ${fmt(b)}`;
      const W=620,H=360,L=55,R=28,T=28,B=65,gw=W-L-R,gh=H-T-B;
      let d=''; for(let i=0;i<=120;i++){const x=i/120,y=ease(x,type,p),px=L+x*gw,py=T+(1-y)*gh;d+=(i?'L':'M')+px.toFixed(2)+' '+py.toFixed(2)+' '}
      const px=L+u*gw,py=T+(1-eu)*gh;
      m.querySelector('#easeSvg').innerHTML=`<defs><linearGradient id="eg" x1="0" x2="1"><stop stop-color="#2563eb"/><stop offset="1" stop-color="#7c3aed"/></linearGradient></defs><g stroke="var(--line)" stroke-width="1"><line x1="${L}" y1="${T}" x2="${L}" y2="${H-B}"/><line x1="${L}" y1="${H-B}" x2="${W-R}" y2="${H-B}"/><line x1="${L}" y1="${T+gh/2}" x2="${W-R}" y2="${T+gh/2}" stroke-dasharray="4 5"/><line x1="${L+gw/2}" y1="${T}" x2="${L+gw/2}" y2="${H-B}" stroke-dasharray="4 5"/></g><path d="${d}" fill="none" stroke="url(#eg)" stroke-width="5" stroke-linecap="round"/><line x1="${px}" y1="${H-B}" x2="${px}" y2="${py}" stroke="#94a3b8" stroke-dasharray="5 5"/><circle cx="${px}" cy="${py}" r="8" fill="#2563eb" stroke="white" stroke-width="3"/><text x="${L}" y="${H-28}" fill="var(--muted)" font-size="12">0</text><text x="${W-R-5}" y="${H-28}" text-anchor="end" fill="var(--muted)" font-size="12">1</text><text x="${L-18}" y="${T+5}" fill="var(--muted)" font-size="12">1</text><text x="${L-18}" y="${H-B+5}" fill="var(--muted)" font-size="12">0</text><text x="${W/2}" y="${H-28}" text-anchor="middle" fill="var(--muted)" font-size="12">u / time</text><circle cx="${L+eu*gw}" cy="${H-22}" r="7" fill="#7c3aed"/><text x="${L+eu*gw}" y="${H-5}" text-anchor="middle" fill="var(--muted)" font-size="10">object</text>`;
      m.querySelector('#easeReadout').innerHTML=`<div class="readout"><small>u</small><strong>${fmt(u,3)}</strong></div><div class="readout"><small>eased(u)</small><strong>${fmt(eu,3)}</strong></div><div class="readout"><small>${tx('出力値','output')}</small><strong>${fmt(value,2)}</strong></div>`;
      const formula=type==='in'?`eased = u^${fmt(p)}`:type==='out'?`eased = 1 - (1-u)^${fmt(p)}`:type==='inout'?`eased = piecewise(In, Out), p=${fmt(p)}`:'eased = u';
      m.querySelector('#easeFormula').textContent=`u = ${fmt(u,3)}\n${formula}\neased = ${fmt(eu,4)}\nvalue = ${fmt(a)} + (${fmt(b)}-${fmt(a)})×${fmt(eu,4)} = ${fmt(value,3)}`;
    }
    [uEl,pEl,sEl,eEl].forEach(x=>x.addEventListener('input',draw));
    const pb=m.querySelector('[data-play]');pb.onclick=()=>{playing=!playing;pb.textContent=playing?'❚❚ '+tx('停止','Pause'):'▶ '+tx('再生','Play');if(playing){startTime=performance.now()-+uEl.value*2200;tick()}};
    m.querySelector('[data-reset]').onclick=()=>{playing=false;cancelAnimationFrame(raf);uEl.value=0;pb.textContent='▶ '+tx('再生','Play');draw()};
    function tick(){if(!playing)return;let u=(performance.now()-startTime)/2200;if(u>=1){u=1;playing=false;pb.textContent='▶ '+tx('再生','Play')}uEl.value=u;draw();if(playing)raf=requestAnimationFrame(tick)}
    draw();
  }

  function renderRotate(m){
    const controls=`${range('rotX','X','X',-180,180,1,110)}${range('rotY','Y','Y',-130,130,1,65)}${range('rotA','Angle θ','Angle θ',-180,180,1,35,'°')}<div class="segmented" data-preset><button data-a="0">0°</button><button data-a="30">30°</button><button data-a="45">45°</button><button data-a="90">90°</button></div>${playBtns()}<div id="rotFormula" class="formula-live"></div>`;
    const stage=`<div class="stage" style="min-height:430px"><svg id="rotSvg" viewBox="0 0 620 430" role="img" aria-label="Coordinate rotation"></svg></div><div id="rotReadout" class="readout-grid"></div>`;
    m.innerHTML=shell('Rotate Position','Rotate Position','点をドラッグ、または角度を変更して回転行列の各項を確認します。','Drag the point or change the angle to inspect every term of the rotation matrix.',controls,stage);
    const xEl=m.querySelector('#rotX'),yEl=m.querySelector('#rotY'),aEl=m.querySelector('#rotA'),svg=m.querySelector('#rotSvg');let playing=false,raf=0,st=0;
    function calc(){const x=+xEl.value,y=+yEl.value,a=+aEl.value,c=Math.cos(deg(a)),s=Math.sin(deg(a));return{x,y,a,c,s,xp:x*c-y*s,yp:x*s+y*c}}
    function draw(){const q=calc(),cx=310,cy=215,scale=1.05;const ox=cx+q.x*scale,oy=cy-q.y*scale,rx=cx+q.xp*scale,ry=cy-q.yp*scale;const axis=180;
      xEl.nextElementSibling; m.querySelector('#rotXOut').textContent=fmt(q.x);m.querySelector('#rotYOut').textContent=fmt(q.y);m.querySelector('#rotAOut').textContent=fmt(q.a)+'°';
      const arcR=48,a0=0,a1=-deg(q.a),ex=cx+arcR*Math.cos(a1),ey=cy+arcR*Math.sin(a1),large=Math.abs(q.a)>180?1:0,sweep=q.a>=0?0:1;
      svg.innerHTML=`<defs><marker id="arr" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3 Z" fill="#2563eb"/></marker></defs><g stroke="var(--line)" stroke-width="1"><line x1="${cx-axis}" y1="${cy}" x2="${cx+axis}" y2="${cy}"/><line x1="${cx}" y1="${cy-axis}" x2="${cx}" y2="${cy+axis}"/></g><text x="${cx+axis+8}" y="${cy+4}" fill="var(--muted)" font-size="12">x</text><text x="${cx+5}" y="${cy-axis-7}" fill="var(--muted)" font-size="12">y</text><line x1="${cx}" y1="${cy}" x2="${ox}" y2="${oy}" stroke="#94a3b8" stroke-width="2" stroke-dasharray="5 5"/><line x1="${cx}" y1="${cy}" x2="${rx}" y2="${ry}" stroke="#2563eb" stroke-width="3.5" marker-end="url(#arr)"/><circle id="dragPoint" cx="${ox}" cy="${oy}" r="9" fill="#94a3b8" stroke="white" stroke-width="3" style="cursor:grab"/><circle cx="${rx}" cy="${ry}" r="9" fill="#2563eb" stroke="white" stroke-width="3"/><text x="${ox+11}" y="${oy-11}" fill="var(--muted)" font-size="12">P(${fmt(q.x)}, ${fmt(q.y)})</text><text x="${rx+11}" y="${ry-11}" fill="#2563eb" font-size="12">P'(${fmt(q.xp,1)}, ${fmt(q.yp,1)})</text><path d="M ${cx+arcR} ${cy} A ${arcR} ${arcR} 0 ${large} ${sweep} ${ex} ${ey}" fill="none" stroke="#7c3aed" stroke-width="3"/><text x="${cx+62*Math.cos(a1/2)}" y="${cy+62*Math.sin(a1/2)}" fill="#7c3aed" font-weight="700" font-size="12">θ</text><line x1="${rx}" y1="${ry}" x2="${rx}" y2="${cy}" stroke="#16a34a" stroke-dasharray="5 5"/><line x1="${rx}" y1="${ry}" x2="${cx}" y2="${ry}" stroke="#e87911" stroke-dasharray="5 5"/>`;
      m.querySelector('#rotReadout').innerHTML=`<div class="readout"><small>x'</small><strong>${fmt(q.xp,2)}</strong></div><div class="readout"><small>y'</small><strong>${fmt(q.yp,2)}</strong></div><div class="readout"><small>x cosθ</small><strong>${fmt(q.x*q.c,2)}</strong></div><div class="readout"><small>-y sinθ</small><strong>${fmt(-q.y*q.s,2)}</strong></div>`;
      m.querySelector('#rotFormula').textContent=`x' = x cosθ - y sinθ\n   = ${fmt(q.x)}×${fmt(q.c,3)} - ${fmt(q.y)}×${fmt(q.s,3)} = ${fmt(q.xp,3)}\ny' = x sinθ + y cosθ\n   = ${fmt(q.x)}×${fmt(q.s,3)} + ${fmt(q.y)}×${fmt(q.c,3)} = ${fmt(q.yp,3)}`;
    }
    [xEl,yEl,aEl].forEach(x=>x.oninput=draw);m.querySelectorAll('[data-preset] button').forEach(b=>b.onclick=()=>{aEl.value=b.dataset.a;draw()});
    svg.addEventListener('pointerdown',e=>{if(e.target.id!=='dragPoint')return;svg.setPointerCapture(e.pointerId);e.preventDefault();const move=ev=>{const r=svg.getBoundingClientRect(),sx=620/r.width,sy=430/r.height,px=(ev.clientX-r.left)*sx,py=(ev.clientY-r.top)*sy;xEl.value=clamp((px-310)/1.05,-180,180);yEl.value=clamp((215-py)/1.05,-130,130);draw()};const up=()=>{svg.removeEventListener('pointermove',move);svg.removeEventListener('pointerup',up)};svg.addEventListener('pointermove',move);svg.addEventListener('pointerup',up)});
    const pb=m.querySelector('[data-play]');pb.onclick=()=>{playing=!playing;pb.textContent=playing?'❚❚ '+tx('停止','Pause'):'▶ '+tx('再生','Play');if(playing){st=performance.now()-((+aEl.value+180)/360)*4000;tick()}};m.querySelector('[data-reset]').onclick=()=>{playing=false;cancelAnimationFrame(raf);aEl.value=35;xEl.value=110;yEl.value=65;pb.textContent='▶ '+tx('再生','Play');draw()};function tick(){if(!playing)return;let t=((performance.now()-st)%4000)/4000;aEl.value=-180+360*t;draw();raf=requestAnimationFrame(tick)}
    draw();
  }

  function renderCamera(m){
    const controls=`${range('objX','Object X','Object X',-200,200,1,130)}${range('objY','Object Y','Object Y',-150,150,1,70)}${range('camX','Camera X','Camera X',-150,150,1,20)}${range('camY','Camera Y','Camera Y',-120,120,1,-10)}${range('camRot','Camera Rotation','Camera Rotation',-90,90,1,15,'°')}${range('camZoom','Camera Zoom','Camera Zoom',.4,2,.01,1.15,'×')}<div id="cameraFormula" class="formula-live"></div>`;
    const stage=`<div class="stage" style="min-height:430px"><svg id="cameraSvg" viewBox="0 0 700 430"></svg></div><div id="cameraStages" class="readout-grid"></div>`;
    m.innerHTML=shell('Camera / Position Lab','Camera / Position Lab','World → Camera差分 → Rotate → Zoom/Screen の4段階を数値と図で同期表示します。','See World → camera offset → rotation → zoom/screen as four synchronized stages.',controls,stage);
    const ids=['objX','objY','camX','camY','camRot','camZoom'];ids.forEach(id=>m.querySelector('#'+id).oninput=draw);
    function draw(){const get=id=>+m.querySelector('#'+id).value,ox=get('objX'),oy=get('objY'),cx=get('camX'),cy=get('camY'),r=get('camRot'),z=get('camZoom');const x0=ox-cx,y0=oy-cy,c=Math.cos(deg(r)),s=Math.sin(deg(r)),rx=x0*c-y0*s,ry=x0*s+y0*c,sx=rx*z,sy=ry*z;ids.forEach(id=>{const el=m.querySelector('#'+id+'Out');if(el)el.textContent=id==='camRot'?fmt(get(id))+'°':id==='camZoom'?fmt(get(id),2)+'×':fmt(get(id))});
      const svg=m.querySelector('#cameraSvg'),p1={x:170,y:215},p2={x:530,y:215},sc=.72;const O={x:p1.x+ox*sc,y:p1.y-oy*sc},C={x:p1.x+cx*sc,y:p1.y-cy*sc},S={x:p2.x+sx*.72,y:p2.y-sy*.72};
      svg.innerHTML=`<defs><marker id="ca" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0L0,6L6,3Z" fill="#2563eb"/></marker></defs><text x="55" y="38" fill="var(--ink)" font-weight="800" font-size="15">WORLD</text><text x="425" y="38" fill="var(--ink)" font-weight="800" font-size="15">SCREEN</text><rect x="40" y="60" width="280" height="310" rx="16" fill="none" stroke="var(--line)"/><rect x="390" y="60" width="280" height="310" rx="16" fill="none" stroke="var(--line)"/><g stroke="var(--line)"><line x1="40" y1="215" x2="320" y2="215"/><line x1="170" y1="60" x2="170" y2="370"/><line x1="390" y1="215" x2="670" y2="215"/><line x1="530" y1="60" x2="530" y2="370"/></g><line x1="${C.x}" y1="${C.y}" x2="${O.x}" y2="${O.y}" stroke="#7c3aed" stroke-width="2" stroke-dasharray="5 5"/><circle cx="${O.x}" cy="${O.y}" r="10" fill="#2563eb"/><text x="${O.x+12}" y="${O.y-10}" fill="#2563eb" font-size="11">Object</text><g transform="translate(${C.x} ${C.y}) rotate(${-r})"><path d="M-12 -8h24v16h-24z M12 -4l10 -7v22l-10 -7z" fill="#7c3aed"/></g><text x="${C.x+12}" y="${C.y+22}" fill="#7c3aed" font-size="11">Camera</text><circle cx="${S.x}" cy="${S.y}" r="10" fill="#16a34a"/><text x="${S.x+12}" y="${S.y-10}" fill="#16a34a" font-size="11">screen</text><path d="M330 215H375" stroke="#2563eb" stroke-width="3" marker-end="url(#ca)"/><text x="352" y="195" text-anchor="middle" fill="var(--muted)" font-size="10">transform</text>`;
      m.querySelector('#cameraStages').innerHTML=`<div class="readout"><small>1 World</small><strong>(${fmt(ox)}, ${fmt(oy)})</strong></div><div class="readout"><small>2 Offset</small><strong>(${fmt(x0)}, ${fmt(y0)})</strong></div><div class="readout"><small>3 Rotate</small><strong>(${fmt(rx,1)}, ${fmt(ry,1)})</strong></div><div class="readout"><small>4 Screen</small><strong>(${fmt(sx,1)}, ${fmt(sy,1)})</strong></div>`;
      m.querySelector('#cameraFormula').textContent=`offset = (${fmt(ox)}-${fmt(cx)}, ${fmt(oy)}-${fmt(cy)}) = (${fmt(x0)}, ${fmt(y0)})\nrotate(${fmt(r)}°) → (${fmt(rx,2)}, ${fmt(ry,2)})\nzoom × ${fmt(z,2)} → (${fmt(sx,2)}, ${fmt(sy,2)})`;
    }draw();
  }

  function renderTimer(m){
    const controls=`${range('timerBpm','BPM','BPM',60,200,1,120)}${range('timerOffset','開始オフセット','Start offset',-2,3,.05,0,'s')}${range('timerSec','Scratch timer','Scratch timer',0,8,.001,0,'s')}${playBtns()}<div id="timerFormula" class="formula-live"></div>`;
    const stage=`<div class="stage" style="min-height:330px"><svg id="timerSvg" viewBox="0 0 700 330"></svg></div><div id="timerReadout" class="readout-grid"></div>`;
    m.innerHTML=shell('Beat Timer Lab','Beat Timer Lab','秒・BPM・拍の関係を動かして確認します。','Explore the relationship between seconds, BPM, and beat position.',controls,stage);let playing=false,raf=0,st=0;const sec=m.querySelector('#timerSec');['timerBpm','timerOffset','timerSec'].forEach(id=>m.querySelector('#'+id).oninput=draw);
    function draw(){const bpm=+m.querySelector('#timerBpm').value,off=+m.querySelector('#timerOffset').value,s=+sec.value,beat=(s-off)*(bpm/60);m.querySelector('#timerBpmOut').textContent=fmt(bpm);m.querySelector('#timerOffsetOut').textContent=fmt(off,2)+'s';m.querySelector('#timerSecOut').textContent=fmt(s,3)+'s';const svg=m.querySelector('#timerSvg'),L=55,R=30,W=700,maxBeat=16,xx=b=>L+clamp(b,0,maxBeat)*(W-L-R)/maxBeat;let ticks='';for(let b=0;b<=maxBeat;b++){const x=xx(b);ticks+=`<line x1="${x}" y1="145" x2="${x}" y2="${b%4===0?180:168}" stroke="${b%4===0?'#2563eb':'var(--line)'}" stroke-width="${b%4===0?2:1}"/><text x="${x}" y="200" text-anchor="middle" fill="var(--muted)" font-size="10">${b}</text>`}svg.innerHTML=`<text x="55" y="55" fill="var(--ink)" font-size="16" font-weight="800">${fmt(bpm)} BPM</text><text x="55" y="82" fill="var(--muted)" font-size="12">1 sec = ${fmt(bpm/60,3)} beats</text><line x1="${L}" y1="145" x2="${W-R}" y2="145" stroke="var(--line)" stroke-width="3"/>${ticks}<circle cx="${xx(beat)}" cy="145" r="11" fill="#7c3aed" stroke="white" stroke-width="3"/><text x="${xx(beat)}" y="120" text-anchor="middle" fill="#7c3aed" font-size="12" font-weight="800">Timer ${fmt(beat,2)}</text><path d="M55 245H645" stroke="var(--line)" stroke-width="2"/><circle cx="${55+s/8*590}" cy="245" r="8" fill="#2563eb"/><text x="55" y="280" fill="var(--muted)" font-size="11">0s</text><text x="645" y="280" text-anchor="end" fill="var(--muted)" font-size="11">8s</text>`;m.querySelector('#timerReadout').innerHTML=`<div class="readout"><small>seconds</small><strong>${fmt(s,3)} s</strong></div><div class="readout"><small>beats/sec</small><strong>${fmt(bpm/60,3)}</strong></div><div class="readout"><small>Timer</small><strong>${fmt(beat,3)} beat</strong></div>`;m.querySelector('#timerFormula').textContent=`Timer = (scratchTimer - offset) × (BPM / 60)\n= (${fmt(s,3)} - ${fmt(off,2)}) × (${fmt(bpm)} / 60)\n= ${fmt(beat,4)} beats`}
    const pb=m.querySelector('[data-play]');pb.onclick=()=>{playing=!playing;pb.textContent=playing?'❚❚ '+tx('停止','Pause'):'▶ '+tx('再生','Play');if(playing){st=performance.now()-+sec.value/8*8000;tick()}};m.querySelector('[data-reset]').onclick=()=>{playing=false;cancelAnimationFrame(raf);sec.value=0;pb.textContent='▶ '+tx('再生','Play');draw()};function tick(){if(!playing)return;let s=((performance.now()-st)%8000)/1000;sec.value=s;draw();raf=requestAnimationFrame(tick)}draw();
  }

  function hash(seed){const x=Math.abs(Math.sin(deg(123.456*seed+78.233*Math.sqrt(Math.abs(seed)+1)))*43758.5453);return x-Math.floor(x)}
  function renderParticle(m){
    const controls=`${range('pTime','Timer','Timer',0,6,.002,2.2)}${range('pPace','発生間隔 Pace','Spawn pace',.05,.5,.01,.14)}${range('pLife','寿命 Length','Lifetime',.3,2,.01,1.15)}${range('pSpeed','半径 / Speed','Radius / Speed',80,420,1,260)}${range('pGravity','Gravity','Gravity',-120,180,1,35)}${range('pSalt','Seed offset','Seed offset',0,4000,1,1000)}${playBtns()}<div id="particleFormula" class="formula-live"></div>`;
    const stage=`<div class="stage" style="min-height:430px"><canvas id="particleCanvas" width="700" height="430"></canvas></div><div id="particleReadout" class="readout-grid"></div>`;
    m.innerHTML=shell('Particle Lab','Particle Lab','時刻を戻しても同じ粒子が同じ軌道へ戻ることを確認できます。','Scrub backward in time and verify that the same particle returns to the same deterministic trajectory.',controls,stage);let playing=false,raf=0,st=0;const time=m.querySelector('#pTime'),canvas=m.querySelector('#particleCanvas'),ctx=canvas.getContext('2d');['pTime','pPace','pLife','pSpeed','pGravity','pSalt'].forEach(id=>m.querySelector('#'+id).oninput=draw);
    function draw(){const t=+time.value,pace=+m.querySelector('#pPace').value,life=+m.querySelector('#pLife').value,speed=+m.querySelector('#pSpeed').value,g=+m.querySelector('#pGravity').value,salt=+m.querySelector('#pSalt').value;[['pTime',3],['pPace',2],['pLife',2],['pSpeed',0],['pGravity',0],['pSalt',0]].forEach(([id,d])=>m.querySelector('#'+id+'Out').textContent=fmt(+m.querySelector('#'+id).value,d));ctx.clearRect(0,0,700,430);ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--panel').trim();ctx.fillRect(0,0,700,430);ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--line').trim();ctx.beginPath();ctx.moveTo(350,0);ctx.lineTo(350,430);ctx.moveTo(0,215);ctx.lineTo(700,215);ctx.stroke();const first=Math.floor((t-life)/pace)+1,last=Math.floor(t/pace);let active=0;for(let n=first;n<=last;n++){const birth=n*pace,age=t-birth;if(age<0||age>=life)continue;active++;const u=age/life,eu=1-Math.pow(1-u,3),rad=speed*eu,ang=hash(n+salt)*Math.PI*2,variation=.8+.4*hash(n+salt+97.31),x=350+Math.cos(ang)*rad*variation,y=215-Math.sin(ang)*rad*variation+g*age*age*.5;const alpha=Math.max(0,1-u);const size=3+7*(1-u)*(.7+.6*hash(n+salt+194.62));ctx.globalAlpha=alpha;ctx.fillStyle=`hsl(${190+120*hash(n+salt+291.93)} 85% 62%)`;ctx.beginPath();ctx.arc(x,y,size,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}ctx.fillStyle='#2563eb';ctx.beginPath();ctx.arc(350,215,6,0,Math.PI*2);ctx.fill();m.querySelector('#particleReadout').innerHTML=`<div class="readout"><small>firstIndex</small><strong>${first}</strong></div><div class="readout"><small>lastIndex</small><strong>${last}</strong></div><div class="readout"><small>${tx('生存粒子','active')}</small><strong>${active}</strong></div><div class="readout"><small>R(seed)</small><strong>${fmt(hash(first+salt),4)}</strong></div>`;m.querySelector('#particleFormula').textContent=`firstIndex = floor((Timer-Length)/Pace)+1 = ${first}\nlastIndex = floor(Timer/Pace) = ${last}\nbirth(n) = n × Pace\nangle(n) = 360 × R(n + ${fmt(salt)})\nR(seed) is deterministic: scrubbing time does not redraw a new random path.`}
    const pb=m.querySelector('[data-play]');pb.onclick=()=>{playing=!playing;pb.textContent=playing?'❚❚ '+tx('停止','Pause'):'▶ '+tx('再生','Play');if(playing){st=performance.now()-+time.value/6*7000;tick()}};m.querySelector('[data-reset]').onclick=()=>{playing=false;cancelAnimationFrame(raf);time.value=0;pb.textContent='▶ '+tx('再生','Play');draw()};function tick(){if(!playing)return;time.value=((performance.now()-st)%7000)/7000*6;draw();raf=requestAnimationFrame(tick)}draw();
  }

  function catmull(p0,p1,p2,p3,t){const t2=t*t,t3=t2*t;return {x:.5*((2*p1.x)+(-p0.x+p2.x)*t+(2*p0.x-5*p1.x+4*p2.x-p3.x)*t2+(-p0.x+3*p1.x-3*p2.x+p3.x)*t3),y:.5*((2*p1.y)+(-p0.y+p2.y)*t+(2*p0.y-5*p1.y+4*p2.y-p3.y)*t2+(-p0.y+3*p1.y-3*p2.y+p3.y)*t3)}}
  function renderSpline(m){
    const controls=`${range('sProgress','Progress t','Progress t',0,1,.001,.36)}${range('sSamples','生成サンプル数','Generated samples',40,500,10,240)}<div class="control"><div class="control-row"><label>${tx('表示','Display')}</label></div><label style="display:flex;gap:8px;align-items:center"><input id="sPoly" type="checkbox" checked> ${tx('制御多角形','Control polygon')}</label><label style="display:flex;gap:8px;align-items:center;margin-top:7px"><input id="sConstruction" type="checkbox" checked> ${tx('de Casteljau中間段階','de Casteljau construction')}</label><label style="display:flex;gap:8px;align-items:center;margin-top:7px"><input id="sAll" type="checkbox" checked> ${tx('未描画部分','Undrawn part')}</label></div><div class="bezier-actions"><button class="primary-btn" type="button" data-add-point>＋ ${tx('制御点','Control point')}</button><button class="ghost-btn" type="button" data-remove-point>－ ${tx('制御点','Control point')}</button></div><button class="ghost-btn" type="button" data-reset-bezier style="width:100%">↺ ${tx('初期形状へ戻す','Reset shape')}</button><div class="bezier-note">${tx('重要：端点P0・PNは曲線上にありますが、中間制御点は通常「通過点」ではありません。曲線を引っ張って形を決めます。','Important: endpoints P0 and PN lie on the curve, but intermediate control points usually do not. They pull the curve and control its shape.')}</div><div id="splineFormula" class="formula-live"></div>`;
    const stage=`<div class="stage" style="min-height:445px"><svg id="splineSvg" viewBox="0 0 700 445" role="img" aria-label="N-degree Bézier curve and de Casteljau construction"></svg></div><div class="bezier-stage-legend" id="bezierLegend"></div><div id="splineReadout" class="readout-grid"></div>`;
    m.innerHTML=shell('N次 Bézier / de Casteljau','N-degree Bézier / de Casteljau','制御点をドラッグし、N+1個の制御点 → N次曲線という関係と、de Casteljauの縮約過程を同時に確認します。','Drag control points and inspect both the N+1 control points → degree N relationship and every level of de Casteljau reduction.',controls,stage);
    const initial=[{x:70,y:330},{x:205,y:80},{x:350,y:320},{x:505,y:105},{x:635,y:290}];
    let pts=initial.map(p=>({...p})),drag=-1;
    const svg=m.querySelector('#splineSvg'),progress=m.querySelector('#sProgress'),samplesEl=m.querySelector('#sSamples'),poly=m.querySelector('#sPoly'),construction=m.querySelector('#sConstruction'),showAll=m.querySelector('#sAll');
    const colors=['#2563eb','#7c3aed','#ec4899','#f59e0b','#16a34a','#0891b2','#dc2626','#9333ea','#475569'];
    const path=arr=>arr.length?arr.map((p,i)=>`${i?'L':'M'}${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(' '):'';
    function casteljau(points,t){const levels=[points.map(p=>({...p}))];while(levels.at(-1).length>1){const prev=levels.at(-1),next=[];for(let i=0;i<prev.length-1;i++)next.push({x:(1-t)*prev[i].x+t*prev[i+1].x,y:(1-t)*prev[i].y+t*prev[i+1].y});levels.push(next)}return levels}
    const at=t=>casteljau(pts,t).at(-1)[0];
    function sampled(n){const out=[];for(let j=0;j<n;j++)out.push(at(n===1?0:j/(n-1)));return out}
    function draw(){
      const t=+progress.value,nSamples=+samplesEl.value,degree=pts.length-1,curve=sampled(nSamples),cut=Math.max(1,Math.floor(t*(curve.length-1))+1),visible=curve.slice(0,cut),levels=casteljau(pts,t); 
      m.querySelector('#sProgressOut').textContent=fmt(t,3);m.querySelector('#sSamplesOut').textContent=nSamples;
      let html='';
      if(showAll.checked)html+=`<path d="${path(curve)}" fill="none" stroke="var(--line)" stroke-width="5" stroke-linecap="round"/>`;
      if(poly.checked)html+=`<path d="${path(pts)}" fill="none" stroke="#94a3b8" stroke-width="1.6" stroke-dasharray="7 6"/>`;
      if(construction.checked){levels.slice(1,-1).forEach((lv,idx)=>{const c=colors[(idx+1)%colors.length];if(lv.length>1)html+=`<path d="${path(lv)}" fill="none" stroke="${c}" stroke-width="1.8" opacity="${Math.max(.35,.8-idx*.08)}"/>`;html+=lv.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="${Math.max(3.5,6-idx*.35)}" fill="${c}" opacity="${Math.max(.5,.92-idx*.07)}" stroke="white" stroke-width="1.5"/>`).join('')})}
      html+=`<path d="${path(visible)}" fill="none" stroke="#7c3aed" stroke-width="11" opacity=".14" stroke-linecap="round"/><path d="${path(visible)}" fill="none" stroke="#2563eb" stroke-width="4.2" stroke-linecap="round"/>`;
      html+=pts.map((p,i)=>`<g class="cp" data-i="${i}" style="cursor:grab"><circle cx="${p.x}" cy="${p.y}" r="11" fill="#2563eb" stroke="white" stroke-width="3"/><text x="${p.x+13}" y="${p.y-13}" fill="var(--muted)" font-size="11" font-weight="800">P${i}</text></g>`).join('');
      const b=levels.at(-1)[0];
      html+=`<circle cx="${b.x}" cy="${b.y}" r="8" fill="#e87911" stroke="white" stroke-width="3"/><text x="${b.x+12}" y="${b.y+20}" fill="#e87911" font-size="11" font-weight="900">B(t)</text>`;
      svg.innerHTML=html;
      const ops=degree*(degree+1)/2;
      m.querySelector('#splineReadout').innerHTML=`<div class="readout"><small>${tx('制御点','control points')}</small><strong>${pts.length}</strong></div><div class="readout"><small>${tx('次数','degree')}</small><strong>${degree}</strong></div><div class="readout"><small>${tx('補間/1点','lerps / point')}</small><strong>${ops}</strong></div><div class="readout"><small>B(t)</small><strong>(${fmt(b.x,1)}, ${fmt(b.y,1)})</strong></div>`;
      m.querySelector('#splineFormula').textContent=`N + 1 control points = degree N\nN = ${pts.length} - 1 = ${degree}\n\nPᵢ⁽ʳ⁾ = (1-t)Pᵢ⁽ʳ⁻¹⁾ + tPᵢ₊₁⁽ʳ⁻¹⁾\nt = ${fmt(t,3)}\n${pts.length} → ${Array.from({length:degree},(_,i)=>pts.length-i-1).join(' → ')}\nB(t) = P₀⁽ᴺ⁾ = (${fmt(b.x,2)}, ${fmt(b.y,2)})\n\n${tx('中間制御点は通常、曲線上の通過点ではない。','Intermediate control points normally do not lie on the curve.')}`;
      const legendLevels=Math.min(degree,6);
      m.querySelector('#bezierLegend').innerHTML=Array.from({length:legendLevels},(_,i)=>`<span><i style="background:${i===0?'#94a3b8':colors[i%colors.length]}"></i>${i===0?tx('制御多角形','control polygon'):`level ${i}`}</span>`).join('')+(degree>=1?`<span><i style="background:#e87911"></i>B(t)</span>`:'');
    }
    [progress,samplesEl,poly,construction,showAll].forEach(el=>el.addEventListener('input',draw));
    m.querySelector('[data-add-point]').onclick=()=>{if(pts.length>=10)return;const a=pts[pts.length-2],b=pts[pts.length-1];pts.splice(pts.length-1,0,{x:(a.x+b.x)/2,y:clamp((a.y+b.y)/2+(pts.length%2?65:-65),35,410)});draw()};
    m.querySelector('[data-remove-point]').onclick=()=>{if(pts.length<=2)return;pts.splice(pts.length-2,1);draw()};
    m.querySelector('[data-reset-bezier]').onclick=()=>{pts=initial.map(p=>({...p}));progress.value=.36;samplesEl.value=240;poly.checked=true;construction.checked=true;showAll.checked=true;draw()};
    svg.addEventListener('pointerdown',e=>{const g=e.target.closest('.cp');if(!g)return;drag=+g.dataset.i;svg.setPointerCapture(e.pointerId)});
    svg.addEventListener('pointermove',e=>{if(drag<0)return;const r=svg.getBoundingClientRect();pts[drag]={x:clamp((e.clientX-r.left)*700/r.width,25,675),y:clamp((e.clientY-r.top)*445/r.height,25,420)};draw()});
    const end=()=>drag=-1;svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);draw();
  }



  function renderStamp(m){
    const controls=`${range('stX','X','X',-180,180,1,45)}${range('stY','Y','Y',-130,130,1,20)}${range('stSize','Size','Size',30,180,1,110,'%')}${range('stDir','Direction','Direction',-180,180,1,18,'°')}${range('stHue','Hue','Hue',0,200,1,112)}${range('stBright','Brightness','Brightness',-70,70,1,15)}${range('stGhost','Ghost','Ghost',0,100,1,8,'%')}<div class="control"><label>${tx('Mode','Mode')}</label><div class="segmented" data-st-mode><button class="active" data-v="direct">${tx('1回描画','Direct')}</button><button data-v="layered">${tx('多重描画','Layered')}</button></div></div><label style="display:flex;gap:8px;align-items:center;font-size:11px;font-weight:800;color:var(--muted)"><input id="stActive" type="checkbox" checked> ${tx('時間条件を満たす','Inside time window')}</label><div class="play-row"><button class="primary-btn" data-run>▶ ${tx('処理を追う','Trace pipeline')}</button><button class="ghost-btn" data-reset>↺ ${tx('初期値','Reset')}</button></div><div id="stampFormula" class="formula-live"></div>`;
    const stage=`<div class="stage" style="min-height:410px"><svg id="stampSvg" viewBox="0 0 700 410"></svg></div><div id="stampPipe" class="readout-grid" style="grid-template-columns:repeat(4,1fr)"></div>`;
    m.innerHTML=shell('Stamp Pipeline','Stamp Pipeline','時間条件 → Position → VFX → Stamp / reset の責務を一つずつ確認します。','Trace the responsibilities: time gate → Position → VFX → Stamp/reset.',controls,stage);
    let mode='direct',step=-1,timers=[];
    const ids=['stX','stY','stSize','stDir','stHue','stBright','stGhost','stActive'];
    ids.forEach(id=>m.querySelector('#'+id).oninput=draw);
    m.querySelectorAll('[data-st-mode] button').forEach(b=>b.onclick=()=>{mode=b.dataset.v;m.querySelectorAll('[data-st-mode] button').forEach(x=>x.classList.toggle('active',x===b));draw()});
    function starPath(cx,cy,r1,r2,n=5){let d='';for(let i=0;i<n*2;i++){const a=-Math.PI/2+i*Math.PI/n,r=i%2?r2:r1,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;d+=(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)+' '}return d+'Z'}
    function draw(){const val=id=>id==='stActive'?m.querySelector('#'+id).checked:+m.querySelector('#'+id).value,x=val('stX'),y=val('stY'),sz=val('stSize'),dir=val('stDir'),h=val('stHue'),br=val('stBright'),gh=val('stGhost'),active=val('stActive');[['stX',''],['stY',''],['stSize','%'],['stDir','°'],['stHue',''],['stBright',''],['stGhost','%']].forEach(([id,u])=>m.querySelector('#'+id+'Out').textContent=fmt(+m.querySelector('#'+id).value)+(u||''));const cx=350+x*.8,cy=205-y*.8,r=55*sz/100,light=clamp(58+br*.32,20,85),opacity=clamp(1-gh/100,0,1);let shapes='';if(active){if(mode==='layered'){shapes+=`<path d="${starPath(0,0,r*1.17,r*.55)}" fill="hsl(${h*1.8} 80% ${clamp(light+18,0,95)}%)" opacity="${opacity*.24}"/><path d="${starPath(0,0,r*1.05,r*.5)}" fill="hsl(${h*1.8} 85% ${clamp(light+6,0,92)}%)" opacity="${opacity*.45}"/>`}shapes+=`<path d="${starPath(0,0,r,r*.46)}" fill="hsl(${h*1.8} 88% ${light}%)" opacity="${opacity}" stroke="white" stroke-opacity=".65" stroke-width="2"/>`}
      m.querySelector('#stampSvg').innerHTML=`<g stroke="var(--line)"><line x1="40" y1="205" x2="660" y2="205"/><line x1="350" y1="35" x2="350" y2="375"/></g><text x="52" y="56" fill="var(--muted)" font-size="11">${tx('最終描画プレビュー','Final render preview')}</text>${active?`<g transform="translate(${cx} ${cy}) rotate(${dir})">${shapes}</g>`:`<g><rect x="235" y="155" width="230" height="95" rx="16" fill="none" stroke="#dc2626" stroke-dasharray="7 6"/><text x="350" y="197" text-anchor="middle" fill="#dc2626" font-weight="800">TIME GATE: OFF</text><text x="350" y="221" text-anchor="middle" fill="var(--muted)" font-size="11">${tx('描画しない','not rendered')}</text></g>`}`;
      const stages=[['1',tx('時間条件','Time gate'),active?tx('描画可能','active'):tx('区間外','inactive')],['2','Position',`(${fmt(x)}, ${fmt(y)}) / ${fmt(sz)}%`],['3','VFX',`H ${fmt(h)} · B ${fmt(br)} · G ${fmt(gh)}`],['4','Stamp / reset',mode==='layered'?tx('多重描画 → reset','layers → reset'):tx('1回描画 → reset','1 pass → reset')]];
      m.querySelector('#stampPipe').innerHTML=stages.map((a,i)=>`<div class="readout" style="${step===i?'outline:2px solid var(--accent);background:var(--accent-soft)':''}"><small>${a[0]} ${a[1]}</small><strong style="font-family:var(--font);font-size:10px">${a[2]}</strong></div>`).join('');
      m.querySelector('#stampFormula').textContent=`time gate = ${active?'PASS':'BLOCK'}\nPosition → x=${fmt(x)}, y=${fmt(y)}, direction=${fmt(dir)}°, size=${fmt(sz)}%\nVFX → hue=${fmt(h)}, brightness=${fmt(br)}, ghost=${fmt(gh)}%\nrender mode = ${mode}\nafter draw → ${tx('必要なら graphic effects を解除','clear graphic effects when required')}`;
    }
    m.querySelector('[data-run]').onclick=()=>{timers.forEach(clearTimeout);timers=[];step=-1;draw();[0,1,2,3].forEach((s,i)=>timers.push(setTimeout(()=>{step=s;draw();if(s===3)timers.push(setTimeout(()=>{step=-1;draw()},650))},i*650)))};
    m.querySelector('[data-reset]').onclick=()=>{timers.forEach(clearTimeout);step=-1;mode='direct';m.querySelectorAll('[data-st-mode] button').forEach(x=>x.classList.toggle('active',x.dataset.v==='direct'));Object.entries({stX:45,stY:20,stSize:110,stDir:18,stHue:112,stBright:15,stGhost:8}).forEach(([id,v])=>m.querySelector('#'+id).value=v);m.querySelector('#stActive').checked=true;draw()};draw();
  }

  function renderMemory(m){
    const controls=`<div class="mini-card"><div class="context-label">${tx('番号規約','Slot policy')}</div><p style="font-size:12px;color:var(--muted);margin:8px 0 0">${tx('番号の意味を固定するのではなく、衝突を避けるための作業領域として扱います。','Treat the ranges as collision-avoidance conventions, not permanent meanings.')}</p></div><div id="memoryInfo" class="formula-live"></div>`;
    const stage=`<div class="stage" style="min-height:420px"><div id="memorySlots" class="memory-grid"></div></div><div class="readout-grid"><div class="readout"><small>1-50</small><strong>${tx('出力・受け渡し','I/O')}</strong></div><div class="readout"><small>51-100</small><strong>${tx('一時計算','temporary')}</strong></div><div class="readout"><small>101-150</small><strong>${tx('大処理・予備','heavy/reserve')}</strong></div></div>`;
    m.innerHTML=shell('*List Memory Map','*List Memory Map','150スロットを作業領域として視覚化します。','Visualize all 150 slots as shared working memory.',controls,stage);const wrap=m.querySelector('#memorySlots');for(let i=1;i<=150;i++){const b=document.createElement('button');b.className='memory-slot';b.textContent=i;b.dataset.n=i;b.style.background=i<=50?'#2563eb':i<=100?'#7c3aed':'#16a34a';wrap.appendChild(b)}function select(n){wrap.querySelectorAll('.memory-slot').forEach(x=>x.classList.toggle('active',+x.dataset.n===n));const r=n<=50?['1-50',tx('出力・定義間の受け渡し','Outputs and cross-definition values')]:n<=100?['51-100',tx('定義内の一時計算','Temporary calculations inside definitions')]:['101-150',tx('Splineなど大きな処理・予備','Large processing such as Spline / reserve')];m.querySelector('#memoryInfo').textContent=`slot ${n}\nrange ${r[0]}\n${r[1]}\n\n${tx('重要: 後で読む値と、呼び出し先が上書きする一時値を同じ番号に置かない。','Important: do not place a value you still need in a slot that a called definition will overwrite.')}`}wrap.onclick=e=>{const b=e.target.closest('.memory-slot');if(b)select(+b.dataset.n)};select(61)
  }

  function renderDependencies(m){
    const controls=`<div class="mini-card"><div class="context-label">Legend</div><div style="display:grid;gap:7px;margin-top:10px;font-size:11px"><span style="color:var(--accent)">■ ${tx('選択中','selected')}</span><span style="color:var(--accent-2)">■ ${tx('必要とする依存','dependencies')}</span><span style="color:var(--good)">■ ${tx('この定義を使う側','used by')}</span></div></div><div id="depText" class="formula-live"></div>`;
    const stage=`<div class="stage" style="min-height:430px"><div id="depStage" class="dependency-stage"></div></div>`;
    m.innerHTML=shell('Dependency Explorer','Dependency Explorer','定義を選ぶと前提と利用先だけを強調します。','Select a definition to highlight only what it depends on and what depends on it.',controls,stage);const defs=D().definitions,st=m.querySelector('#depStage');defs.forEach(d=>{const b=document.createElement('button');b.className='dep-node';b.dataset.id=d.id;b.textContent=d.name;st.appendChild(b)});function select(id){const d=defs.find(x=>x.id===id);st.querySelectorAll('.dep-node').forEach(n=>{const nid=n.dataset.id;n.classList.toggle('selected',nid===id);n.classList.toggle('dep',d.deps.includes(nid));n.classList.toggle('used',d.usedBy.includes(nid))});const names=ids=>ids.length?ids.map(x=>defs.find(d=>d.id===x)?.name||x).join(' → '):'—';m.querySelector('#depText').textContent=`${d.name}\n\n${tx('依存','depends on')}: ${names(d.deps)}\n${tx('利用先','used by')}: ${names(d.usedBy)}\n\n${lang()==='en'?d.en:d.ja}`};st.onclick=e=>{const b=e.target.closest('.dep-node');if(b)select(b.dataset.id)};select('stamp')
  }

  function setRange(root,id,value){const el=root.querySelector('#'+id);if(!el)return;const lo=Number(el.min),hi=Number(el.max);el.value=(Number.isFinite(lo)&&Number.isFinite(hi))?clamp(value,lo,hi):value;el.dispatchEvent(new Event('input',{bubbles:true}))}
  function click(root,sel){root.querySelector(sel)?.click()}
  function attachAutoPlay(id,root){
    const shell=root.querySelector('.lab-shell'); if(!shell) return null;
    const bar=document.createElement('div');
    bar.className='lab-autoplay-bar';
    bar.innerHTML=`<div class="lab-autoplay-copy"><strong>${tx('自動デモ','Automatic demo')}</strong><small>${tx('主要パラメータを自動で動かします。OFFにすると手動操作だけになります。','Animates the key parameter automatically. Turn it off for manual-only control.')}</small></div><label class="auto-switch"><input type="checkbox" aria-label="Auto Play"><span class="auto-switch-track" aria-hidden="true"></span><span class="auto-switch-state">ON</span></label>`;
    shell.querySelector('.lab-head')?.insertAdjacentElement('afterend',bar);
    let enabled=false,raf=0,last=0,cycle=0,startAt=performance.now();
    const sw=bar.querySelector('input'),state=bar.querySelector('.auto-switch-state');
    function frame(now){
      if(!enabled||!root.isConnected){raf=0;return}
      const t=(now-startAt)/1000;
      if(id==='easing') setRange(root,'easeU',(t%3.2)/3.2);
      else if(id==='rotate') setRange(root,'rotA',-180+((t%5.2)/5.2)*360);
      else if(id==='timer') setRange(root,'timerSec',(t%8));
      else if(id==='particle') setRange(root,'pTime',((t%7)/7)*6);
      else if(id==='spline') setRange(root,'sProgress',(t%4.2)/4.2);
      else if(id==='camera'){setRange(root,'camRot',Math.sin(t*.78)*48);setRange(root,'camZoom',1.15+Math.sin(t*.52)*.42);setRange(root,'camX',20+Math.sin(t*.39)*65)}
      else if(id==='stamp'){setRange(root,'stDir',((t*42+198)%360)-180);setRange(root,'stHue',(112+t*24)%200); if(now-last>2800){last=now;click(root,'[data-run]')}}
      else if(id==='memory'){if(now-last>150){last=now;const nodes=[...root.querySelectorAll('.memory-slot')]; if(nodes.length){nodes[cycle%nodes.length].click();cycle++}}}
      else if(id==='dependencies'){if(now-last>1500){last=now;const nodes=[...root.querySelectorAll('.dep-node')]; if(nodes.length){nodes[cycle%nodes.length].click();cycle++}}}
      raf=requestAnimationFrame(frame)
    }
    function setEnabled(v){enabled=v;sw.checked=v;state.textContent=v?'ON':'OFF';localStorage.setItem('ttro-lab-autoplay',v?'on':'off'); if(enabled&&!raf){startAt=performance.now();raf=requestAnimationFrame(frame)} if(!enabled&&raf){cancelAnimationFrame(raf);raf=0}}
    sw.addEventListener('change',()=>setEnabled(sw.checked));
    shell.addEventListener('click',e=>{if(!e.isTrusted) return; if(e.target.closest('[data-play],[data-run]')&&sw.checked) setEnabled(false)},true);
    return {setEnabled};
  }


  const renderers={easing:renderEasing,rotate:renderRotate,camera:renderCamera,timer:renderTimer,stamp:renderStamp,particle:renderParticle,spline:renderSpline,memory:renderMemory,dependencies:renderDependencies};
  window.LABS={
    ids:Object.keys(renderers),
    names:{easing:['Easing','Easing'],rotate:['Rotate Position','Rotate Position'],camera:['Camera / Position','Camera / Position'],timer:['Timer','Timer'],stamp:['Stamp','Stamp'],particle:['Particle','Particle'],spline:['N次 Bézier','N-degree Bézier'],memory:['*List','*List'],dependencies:['依存関係','Dependencies']},
    render(id,mount){(renderers[id]||renderers.easing)(mount); const controller=attachAutoPlay(id,mount); if(controller) controller.setEnabled(localStorage.getItem('ttro-lab-autoplay')!=='off')}
  };
})();
